version: '3'
services:
  database:
    container_name: gcbapi-database
    image: postgres
    environment:
      - POSTGRES_DB=gcbapi
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - '5432:5432'
